import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:lidarmesure/models/session.dart';
import 'package:lidarmesure/models/user.dart';
import 'package:lidarmesure/models/foot_metrics.dart';

class PdfReportService {
  static Future<Uint8List> generateSessionReport({
    required Session session,
    required Patient patient,
    bool isFrench = true,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(patient, isFrench),
        footer: (context) => _buildFooter(context, isFrench),
        build: (context) => [
          _buildSessionInfo(session, dateFormat, isFrench),
          pw.SizedBox(height: 20),
          _buildPatientInfo(patient, isFrench),
          pw.SizedBox(height: 20),
          if (session.footMetrics.isNotEmpty) ...[
            _buildMetricsSection(session.footMetrics, isFrench),
            pw.SizedBox(height: 20),
          ],
          _buildAnalysisSection(session, isFrench),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(Patient patient, bool isFrench) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 20),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 1)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'LiDAR Mesure',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue800,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                isFrench ? 'Rapport de Scan Podologique' : 'Podiatric Scan Report',
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
              ),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.blue50,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  patient.fullName,
                  style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  '${isFrench ? 'Ne(e) le' : 'Born on'} ${patient.formattedDateNaissance}',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context, bool isFrench) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 1)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            isFrench 
                ? 'Genere par LiDAR Mesure - ${DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now())}'
                : 'Generated by LiDAR Mesure - ${DateFormat('MM/dd/yyyy HH:mm').format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
          pw.Text(
            'Page ${context.pageNumber}/${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSessionInfo(Session session, DateFormat dateFormat, bool isFrench) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            isFrench ? 'Informations de la Session' : 'Session Information',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              _infoItem(isFrench ? 'Date' : 'Date', dateFormat.format(session.createdAt)),
              pw.SizedBox(width: 40),
              _infoItem(isFrench ? 'Statut' : 'Status', _getStatusLabel(session.status, isFrench)),
              pw.SizedBox(width: 40),
              _infoItem(isFrench ? 'Valide' : 'Valid', session.valid ? (isFrench ? 'Oui' : 'Yes') : (isFrench ? 'Non' : 'No')),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              _infoItem('ID Session', session.id.substring(0, 8).toUpperCase()),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPatientInfo(Patient patient, bool isFrench) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            isFrench ? 'Informations du Patient' : 'Patient Information',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              pw.Expanded(child: _infoItem(isFrench ? 'Nom complet' : 'Full Name', patient.fullName)),
              pw.Expanded(child: _infoItem(isFrench ? 'Sexe' : 'Gender', _getGenderLabel(patient.sexe, isFrench))),
              pw.Expanded(child: _infoItem('Age', '${patient.age} ${isFrench ? 'ans' : 'years'}')),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(child: _infoItem(isFrench ? 'Taille' : 'Height', '${patient.taille.toStringAsFixed(0)} cm')),
              pw.Expanded(child: _infoItem(isFrench ? 'Poids' : 'Weight', '${patient.poids.toStringAsFixed(1)} kg')),
              pw.Expanded(child: _infoItem(isFrench ? 'Pointure' : 'Shoe Size', patient.pointure)),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(child: _infoItem(isFrench ? 'Telephone' : 'Phone', patient.telephone)),
              pw.Expanded(flex: 2, child: _infoItem(isFrench ? 'Adresse' : 'Address', patient.adresse)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildMetricsSection(List<FootMetrics> metrics, bool isFrench) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            isFrench ? 'Mesures des Pieds' : 'Foot Measurements',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 15),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.blue100),
                children: [
                  _tableHeader(isFrench ? 'Pied' : 'Foot'),
                  _tableHeader(isFrench ? 'Longueur' : 'Length'),
                  _tableHeader(isFrench ? 'Largeur' : 'Width'),
                  _tableHeader(isFrench ? 'Confiance' : 'Confidence'),
                ],
              ),
              ...metrics.map((m) => pw.TableRow(
                children: [
                  _tableCell(m.side == FootSide.droite 
                      ? (isFrench ? 'Pied Droit' : 'Right Foot')
                      : (isFrench ? 'Pied Gauche' : 'Left Foot')),
                  _tableCell('${m.longueur.toStringAsFixed(1)} cm'),
                  _tableCell('${m.largeur.toStringAsFixed(1)} cm'),
                  _tableCell('${(m.confidence * 100).toStringAsFixed(0)}%'),
                ],
              )),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildAnalysisSection(Session session, bool isFrench) {
    final hasQuestionnaires = session.questionnaires.isNotEmpty;
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            isFrench ? 'Analyse et Observations' : 'Analysis and Observations',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          if (hasQuestionnaires) ...[
            pw.Text(
              isFrench ? 'Questionnaire Medical:' : 'Medical Questionnaire:',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 5),
            ...session.questionnaires.map((q) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 4),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('• ', style: const pw.TextStyle(fontSize: 10)),
                  pw.Expanded(
                    child: pw.Text(
                      q.cleDeLaQuestion,
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ),
                ],
              ),
            )),
          ] else ...[
            pw.Text(
              isFrench 
                  ? 'Aucune observation supplementaire enregistree pour cette session.'
                  : 'No additional observations recorded for this session.',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ],
          pw.SizedBox(height: 20),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  isFrench ? 'Notes du praticien:' : 'Practitioner Notes:',
                  style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 5),
                pw.Container(
                  height: 60,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _infoItem(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        pw.SizedBox(height: 2),
        pw.Text(value, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static pw.Widget _tableCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 10),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static String _getStatusLabel(SessionStatus status, bool isFrench) {
    switch (status) {
      case SessionStatus.pending:
        return isFrench ? 'En cours' : 'Pending';
      case SessionStatus.completed:
        return isFrench ? 'Termine' : 'Completed';
      case SessionStatus.cancelled:
        return isFrench ? 'Annule' : 'Cancelled';
    }
  }

  static String _getGenderLabel(int sexe, bool isFrench) {
    if (sexe == 0) return isFrench ? 'Homme' : 'Male';
    if (sexe == 1) return isFrench ? 'Femme' : 'Female';
    return isFrench ? 'Autre' : 'Other';
  }

  static Future<void> printReport({
    required Session session,
    required Patient patient,
    bool isFrench = true,
  }) async {
    final pdfData = await generateSessionReport(
      session: session,
      patient: patient,
      isFrench: isFrench,
    );
    
    await Printing.layoutPdf(
      onLayout: (format) async => pdfData,
      name: 'LiDAR_Mesure_${patient.fullName.replaceAll(' ', '_')}_${DateFormat('yyyyMMdd').format(session.createdAt)}.pdf',
    );
  }

  static Future<void> sharePdf({
    required Session session,
    required Patient patient,
    bool isFrench = true,
  }) async {
    final pdfData = await generateSessionReport(
      session: session,
      patient: patient,
      isFrench: isFrench,
    );
    
    await Printing.sharePdf(
      bytes: pdfData,
      filename: 'LiDAR_Mesure_${patient.fullName.replaceAll(' ', '_')}_${DateFormat('yyyyMMdd').format(session.createdAt)}.pdf',
    );
  }
}
